### ISSUE TITLE
Add support for POL Contract

### ISSUE THREAD

**Issue by Lesigh-3100** [bancorprotocol/fastlane-bot#109]
## Subtasks

- [x] Preprocessing - Add exchange’s pool metadata
- [x] Preprocessing - Add contract addresses
- [x] Data gathering - Create exchange class
- [x] Data gathering - Create pool Class
- [x] Data gathering - Add exchange ABIs
- [x] Data gathering - Add trade event structure
- [x] Data gathering - Add custom handling for exchange
- [x] Transaction handling - custom inputs
- [x] Arb Contract - integrate exchange

## Bugs
- [ ] Data gathering - the token balances need to come from calling the tokenContract.balanceOf(CarbonPOL.address) at least on the first run of the bot (currently using token prices)
- [ ] Run - in main.py you are sending handle_replay_from_block the polling_interval instead of the replay_from_block
- [ ] Data gathering - prices need to be encoded if you are handling them exactly like carbon orders
