### ISSUE TITLE
Checklist for Adding Tests to Bancor POL Contract Support

### ISSUE THREAD

**Issue by mikewcasale** [bancorprotocol/fastlane-bot#116]
### Preliminary Steps

- [ ] Cleanup `bancor_pol` print statements and logging.
- [ ] Identify all places in the codebase where one-off Tenderly hacks exist.
- [ ] Confirm that each Tenderly-specific hack has a corresponding mainnet process.

### Testing

- [ ] Write tests to ensure the correct process (Mainnet or Tenderly) is executed.
- [ ] Add `bancor_pol` exchange class to the existing tests in the "Exchanges" notebook.
- [ ] Add `bancor_pol` pool class to the existing tests in the "Pools" notebook.
- [ ] Identify new utility functions created specifically for `bancor_pol`.
- [ ] Write tests for these new utility functions.
