### ISSUE TITLE
Add Support for Balancer Exchange

### ISSUE THREAD

**Issue by mikewcasale** [bancorprotocol/fastlane-bot#70]

**Comment by Lesigh-3100** [comment]
## Subtasks

- [ ] Preprocessing - Add exchange’s pool metadata
- [ ] Preprocessing - Add exchange addresses
- [ ] Data gathering - Create exchange class
- [ ] Data gathering - Create pool Class
- [ ] Data gathering - Add exchange ABIs
- [ ] Data gathering - Add trade event structure
- [ ] Data gathering - Add custom handling for exchange
- [ ] Optimizer - Optimize
- [ ] Opp processing - data validation
- [ ] Opp processing - 
- [ ] Opp processing - 
- [ ] Opp processing - 
- [ ] Transaction handling - custom inputs
- [ ] Arb Contract - integrate exchange
